export const Data = [
    {
        id: 1,
        name: "Gyandeep sr. sec. school",
        address: "Sector 18A,Dwarka,Delhi",
        imgUrl: "https://www.kasigaschool.com/wp-content/uploads/2019/12/Boarding-life-400x257.jpg",
        fees: "10,500",
        board: "CBSE",
        classes: "1-12",
        category: "All Cities",
        ownership: "Private",
        YearOfEstablishment: 1984,
        coedStatus: "Co-Education",
        CampusSize: "2 Acres",
        CampusType: "Urban",
        RegistrationFees: "₹25",
        AdmissionFees: "₹200",
        TuitionFees: "₹3,175",
        AnnualFees: "₹7,500",
        DevelopmentFees: "₹5,715",
        TransportationFees: "₹2,000-3,000",
        otherFees: "₹16,500",
        MiscFees: "₹5,000",
        TotalCost: "₹73,040",
        MonthyCost: "₹6,069",
        classesOffered: "Play Way- Class 12",
        LanguageOfInstruction: "English",
        AcademicSession: "April To March",
        SchoolFormat: "Day School",
        StudentFacultyRatio: "12:1",
        EligibilityCriteria: "NA",
        WrittenTest: "No",
        TotalSeats: 75,
        ParentsInteraction: "No",
        FormAvailability: "online",
        FormPayment: "online",
        SchoolTiming: "07:40AM TO 12:30PM",
        officeTiming: "NA",
        TotalCost: "₹1,23,925",
        MonthyCost: "₹10,309",
        liked:false

    },
    {
        id: 2,
        name: "Kids corner happy sr. sec. school",
        address: "Near jain mandir,Firozabad",
        imgUrl: "https://rbkei.org/wp-content/uploads/2021/01/School-Slider-03.jpg",
        fees: "10,800",
        board: "CBSE",
        classes: "1-12",
        category: "Agra",
        ownership: "Private",
        YearOfEstablishment: 1984,
        coedStatus: "Co-Education",
        CampusSize: "2 Acres",
        CampusType: "Urban",
        RegistrationFees: "₹25",
        AdmissionFees: "₹200",
        TuitionFees: "₹3,175",
        AnnualFees: "₹7,500",
        DevelopmentFees: "₹5,715",
        TransportationFees: "₹2,000-3,000",
        otherFees: "₹16,500",
        MiscFees: "₹5,000",
        TotalCost: "₹73,040",
        MonthyCost: "₹6,069",
        classesOffered: "Play Way- Class 12",
        LanguageOfInstruction: "English",
        AcademicSession: "April To March",
        SchoolFormat: "Day School",
        StudentFacultyRatio: "12:1",
        EligibilityCriteria: "NA",
        WrittenTest: "No",
        TotalSeats: 75,
        ParentsInteraction: "No",
        FormAvailability: "online",
        FormPayment: "online",
        SchoolTiming: "07:40AM TO 12:30PM",
        officeTiming: "NA",
        TotalCost: "₹1,23,925",
        MonthyCost: "₹10,309"


    },
    {
        id: 3,
        name: "St. Johns School",
        address: "Banglore",
        imgUrl: "https://images.livemint.com/img/2021/07/01/600x338/MP2-kYiB--621x414@LiveMint_1625139958457.jpg",
        fees: "10,200",
        board: "CBSE",
        classes: "1-12",
        category: "Banglore",
        ownership: "Private",
        YearOfEstablishment: 1984,
        coedStatus: "Co-Education",
        CampusSize: "2 Acres",
        CampusType: "Urban",
        RegistrationFees: "₹25",
        AdmissionFees: "₹200",
        TuitionFees: "₹3,175",
        AnnualFees: "₹7,500",
        DevelopmentFees: "₹5,715",
        TransportationFees: "₹2,000-3,000",
        otherFees: "₹16,500",
        MiscFees: "₹5,000",
        TotalCost: "₹73,040",
        MonthyCost: "₹6,069",
        classesOffered: "Play Way- Class 12",
        LanguageOfInstruction: "English",
        AcademicSession: "April To March",
        SchoolFormat: "Day School",
        StudentFacultyRatio: "12:1",
        EligibilityCriteria: "NA",
        WrittenTest: "No",
        TotalSeats: 75,
        ParentsInteraction: "No",
        FormAvailability: "online",
        FormPayment: "online",
        SchoolTiming: "07:40AM TO 12:30PM",
        officeTiming: "NA",
        TotalCost: "₹1,23,925",
        MonthyCost: "₹10,309"


    },
    {
        id: 4,
        name: "St. Mary",
        address: "Agra",
        imgUrl: "https://images.livemint.com/img/2021/07/01/600x338/MP2-kYiB--621x414@LiveMint_1625139958457.jpg",
        fees: "10,200",
        board: "CBSE",
        classes: "1-12",
        category: "Thane",
        ownership: "Private",
        YearOfEstablishment: 1984,
        coedStatus: "Co-Education",
        CampusSize: "2 Acres",
        CampusType: "Urban",
        RegistrationFees: "₹25",
        AdmissionFees: "₹200",
        TuitionFees: "₹3,175",
        AnnualFees: "₹7,500",
        DevelopmentFees: "₹5,715",
        TransportationFees: "₹2,000-3,000",
        otherFees: "₹16,500",
        MiscFees: "₹5,000",
        TotalCost: "₹73,040",
        MonthyCost: "₹6,069",
        classesOffered: "Play Way- Class 12",
        LanguageOfInstruction: "English",
        AcademicSession: "April To March",
        SchoolFormat: "Day School",
        StudentFacultyRatio: "12:1",
        EligibilityCriteria: "NA",
        WrittenTest: "No",
        TotalSeats: 75,
        ParentsInteraction: "No",
        FormAvailability: "online",
        FormPayment: "online",
        SchoolTiming: "07:40AM TO 12:30PM",
        officeTiming: "NA",
        TotalCost: "₹1,23,925",
        MonthyCost: "₹10,309"


    },
    {
        id: 5,
        name: "St. Johns School",
        address: "Agra",
        imgUrl: "https://images.livemint.com/img/2021/07/01/600x338/MP2-kYiB--621x414@LiveMint_1625139958457.jpg",
        fees: "10,200",
        board: "CBSE",
        classes: "1-12",
        category: "Mumbai",
        ownership: "Private",
        YearOfEstablishment: 1984,
        coedStatus: "Co-Education",
        CampusSize: "2 Acres",
        CampusType: "Urban",
        RegistrationFees: "₹25",
        AdmissionFees: "₹200",
        TuitionFees: "₹3,175",
        AnnualFees: "₹7,500",
        DevelopmentFees: "₹5,715",
        TransportationFees: "₹2,000-3,000",
        otherFees: "₹16,500",
        MiscFees: "₹5,000",
        TotalCost: "₹73,040",
        MonthyCost: "₹6,069",
        classesOffered: "Play Way- Class 12",
        LanguageOfInstruction: "English",
        AcademicSession: "April To March",
        SchoolFormat: "Day School",
        StudentFacultyRatio: "12:1",
        EligibilityCriteria: "NA",
        WrittenTest: "No",
        TotalSeats: 75,
        ParentsInteraction: "No",
        FormAvailability: "online",
        FormPayment: "online",
        SchoolTiming: "07:40AM TO 12:30PM",
        officeTiming: "NA",
        TotalCost: "₹1,23,925",
        MonthyCost: "₹10,309"


    },
    {
        id: 6,
        name: "Sri Shakti School",
        address: "Sector 18A,Dwarka,Pune",
        imgUrl: "https://www.kasigaschool.com/wp-content/uploads/2019/12/Boarding-life-400x257.jpg",
        fees: "10,500",
        board: "CBSE",
        classes: "1-12",
        category: "Pune",
        ownership: "Private",
        YearOfEstablishment: 1984,
        coedStatus: "Co-Education",
        CampusSize: "2 Acres",
        CampusType: "Urban",
        RegistrationFees: "₹25",
        AdmissionFees: "₹200",
        TuitionFees: "₹3,175",
        AnnualFees: "₹7,500",
        DevelopmentFees: "₹5,715",
        TransportationFees: "₹2,000-3,000",
        otherFees: "₹16,500",
        MiscFees: "₹5,000",
        TotalCost: "₹73,040",
        MonthyCost: "₹6,069",
        classesOffered: "Play Way- Class 12",
        LanguageOfInstruction: "English",
        AcademicSession: "April To March",
        SchoolFormat: "Day School",
        StudentFacultyRatio: "12:1",
        EligibilityCriteria: "NA",
        WrittenTest: "No",
        TotalSeats: 75,
        ParentsInteraction: "No",
        FormAvailability: "online",
        FormPayment: "online",
        SchoolTiming: "07:40AM TO 12:30PM",
        officeTiming: "NA",
        TotalCost: "₹1,23,925",
        MonthyCost: "₹10,309"


    },
    {
        id: 7,
        name: "Dr. Maria Residential Academy",
        address: "Sector 18A,Dwarka,Agra",
        imgUrl: "https://media.istockphoto.com/photos/children-cheering-in-classroom-picture-id1148218795?s=612x612",
        fees: "10,500",
        board: "CBSE",
        classes: "1-12",
        category: "Agra",
        ownership: "Private",
        YearOfEstablishment: 1984,
        coedStatus: "Co-Education",
        CampusSize: "2 Acres",
        CampusType: "Urban",
        RegistrationFees: "₹25",
        AdmissionFees: "₹200",
        TuitionFees: "₹3,175",
        AnnualFees: "₹7,500",
        DevelopmentFees: "₹5,715",
        TransportationFees: "₹2,000-3,000",
        otherFees: "₹16,500",
        MiscFees: "₹5,000",
        TotalCost: "₹73,040",
        MonthyCost: "₹6,069",
        classesOffered: "Play Way- Class 12",
        LanguageOfInstruction: "English",
        AcademicSession: "April To March",
        SchoolFormat: "Day School",
        StudentFacultyRatio: "12:1",
        EligibilityCriteria: "NA",
        WrittenTest: "No",
        TotalSeats: 75,
        ParentsInteraction: "No",
        FormAvailability: "online",
        FormPayment: "online",
        SchoolTiming: "07:40AM TO 12:30PM",
        officeTiming: "NA",
        TotalCost: "₹1,23,925",
        MonthyCost: "₹10,309"


    },
    {
        id: 8,
        name: "Sri Venkateshwar International School",
        address: "Sector 18A,Dwarka,South West Delhi",
        imgUrl: "	https://cdn.dnaindia.com/sites/default/files/styles/full/public/2018/09/08/728490-schools-031017.jpg",
        fees: "10,500",
        board: "CBSE",
        classes: "1-10",
        category: "Mathura",
        ownership: "Private",
        YearOfEstablishment: 1984,
        coedStatus: "Co-Education",
        CampusSize: "2 Acres",
        CampusType: "Urban",
        RegistrationFees: "₹25",
        AdmissionFees: "₹200",
        TuitionFees: "₹3,175",
        AnnualFees: "₹7,500",
        DevelopmentFees: "₹5,715",
        TransportationFees: "₹2,000-3,000",
        otherFees: "₹16,500",
        MiscFees: "₹5,000",
        TotalCost: "₹73,040",
        MonthyCost: "₹6,069",
        classesOffered: "Play Way- Class 12",
        LanguageOfInstruction: "English",
        AcademicSession: "April To March",
        SchoolFormat: "Day School",
        StudentFacultyRatio: "12:1",
        EligibilityCriteria: "NA",
        WrittenTest: "No",
        TotalSeats: 75,
        ParentsInteraction: "No",
        FormAvailability: "online",
        FormPayment: "online",
        SchoolTiming: "07:40AM TO 12:30PM",
        officeTiming: "NA",
        TotalCost: "₹1,23,925",
        MonthyCost: "₹10,309"


    },
    {
        id: 9,
        name: "Valentine's School",
        address: "vailentine Park,Gurugram",
        imgUrl: "https://images.livemint.com/img/2021/07/01/600x338/MP2-kYiB--621x414@LiveMint_1625139958457.jpg",
        fees: "10,200",
        board: "CBSE",
        classes: "1-12",
        category: "Gurugram",
        ownership: "Private",
        YearOfEstablishment: 1984,
        coedStatus: "Co-Education",
        CampusSize: "2 Acres",
        CampusType: "Urban",
        RegistrationFees: "₹25",
        AdmissionFees: "₹200",
        TuitionFees: "₹3,175",
        AnnualFees: "₹7,500",
        DevelopmentFees: "₹5,715",
        TransportationFees: "₹2,000-3,000",
        otherFees: "₹16,500",
        MiscFees: "₹5,000",
        TotalCost: "₹73,040",
        MonthyCost: "₹6,069",
        classesOffered: "Play Way- Class 12",
        LanguageOfInstruction: "English",
        AcademicSession: "April To March",
        SchoolFormat: "Day School",
        StudentFacultyRatio: "12:1",
        EligibilityCriteria: "NA",
        WrittenTest: "No",
        TotalSeats: 75,
        ParentsInteraction: "No",
        FormAvailability: "online",
        FormPayment: "online",
        SchoolTiming: "07:40AM TO 12:30PM",
        officeTiming: "NA",
        TotalCost: "₹1,23,925",
        MonthyCost: "₹10,309"


    },
    {
        id: 10,
        name: "Genius School",
        address: "Mantola, Navi Mumbai",
        imgUrl: "https://schools.thelearningpoint.net/pics-cbse/schoolPic65837.JPG",
        fees: "10,200",
        board: "CBSE",
        classes: "1-12",
        category: "Navi Mumbai",
        ownership: "Private",
        YearOfEstablishment: 1984,
        coedStatus: "Co-Education",
        CampusSize: "2 Acres",
        CampusType: "Urban",
        RegistrationFees: "₹25",
        AdmissionFees: "₹200",
        TuitionFees: "₹3,175",
        AnnualFees: "₹7,500",
        DevelopmentFees: "₹5,715",
        TransportationFees: "₹2,000-3,000",
        otherFees: "₹16,500",
        MiscFees: "₹5,000",
        TotalCost: "₹73,040",
        MonthyCost: "₹6,069",
        classesOffered: "Play Way- Class 12",
        LanguageOfInstruction: "English",
        AcademicSession: "April To March",
        SchoolFormat: "Day School",
        StudentFacultyRatio: "12:1",
        EligibilityCriteria: "NA",
        WrittenTest: "No",
        TotalSeats: 75,
        ParentsInteraction: "No",
        FormAvailability: "online",
        FormPayment: "online",
        SchoolTiming: "07:40AM TO 12:30PM",
        officeTiming: "NA",
        TotalCost: "₹1,23,925",
        MonthyCost: "₹10,309"


    },
    {
        id: 11,
        name: "St. Johns School",
        address: "Ghaziabad",
        imgUrl: "https://images.livemint.com/img/2021/07/01/600x338/MP2-kYiB--621x414@LiveMint_1625139958457.jpg",
        fees: "10,200",
        board: "CBSE",
        classes: "1-12",
        category: "Ghaziabad",
        ownership: "Private",
        YearOfEstablishment: 1984,
        coedStatus: "Co-Education",
        CampusSize: "2 Acres",
        CampusType: "Urban",
        RegistrationFees: "₹25",
        AdmissionFees: "₹200",
        TuitionFees: "₹3,175",
        AnnualFees: "₹7,500",
        DevelopmentFees: "₹5,715",
        TransportationFees: "₹2,000-3,000",
        otherFees: "₹16,500",
        MiscFees: "₹5,000",
        TotalCost: "₹73,040",
        MonthyCost: "₹6,069",
        classesOffered: "Play Way- Class 12",
        LanguageOfInstruction: "English",
        AcademicSession: "April To March",
        SchoolFormat: "Day School",
        StudentFacultyRatio: "12:1",
        EligibilityCriteria: "NA",
        WrittenTest: "No",
        TotalSeats: 75,
        ParentsInteraction: "No",
        FormAvailability: "online",
        FormPayment: "online",
        SchoolTiming: "07:40AM TO 12:30PM",
        officeTiming: "NA",
        TotalCost: "₹1,23,925",
        MonthyCost: "₹10,309"


    },
    {
        id: 12,
        name: "St. Mary School",
        address: "Vadodra",
        imgUrl: "https://images.livemint.com/img/2021/07/01/600x338/MP2-kYiB--621x414@LiveMint_1625139958457.jpg",
        fees: "10,200",
        board: "CBSE",
        classes: "1-12",
        category: "Vadodra",
        ownership: "Private",
        YearOfEstablishment: 1984,
        coedStatus: "Co-Education",
        CampusSize: "2 Acres",
        CampusType: "Urban",
        RegistrationFees: "₹25",
        AdmissionFees: "₹200",
        TuitionFees: "₹3,175",
        AnnualFees: "₹7,500",
        DevelopmentFees: "₹5,715",
        TransportationFees: "₹2,000-3,000",
        otherFees: "₹16,500",
        MiscFees: "₹5,000",
        TotalCost: "₹73,040",
        MonthyCost: "₹6,069",
        classesOffered: "Play Way- Class 12",
        LanguageOfInstruction: "English",
        AcademicSession: "April To March",
        SchoolFormat: "Day School",
        StudentFacultyRatio: "12:1",
        EligibilityCriteria: "NA",
        WrittenTest: "No",
        TotalSeats: 75,
        ParentsInteraction: "No",
        FormAvailability: "online",
        FormPayment: "online",
        SchoolTiming: "07:40AM TO 12:30PM",
        officeTiming: "NA",
        TotalCost: "₹1,23,925",
        MonthyCost: "₹10,309"


    },
    {
        id: 13,
        name: "St.Maricom School",
        address: "Nashik",
        imgUrl: "https://images.livemint.com/img/2021/07/01/600x338/MP2-kYiB--621x414@LiveMint_1625139958457.jpg",
        fees: "10,200",
        board: "CBSE",
        classes: "1-12",
        category: "Nashik",
        ownership: "Private",
        YearOfEstablishment: 1984,
        coedStatus: "Co-Education",
        CampusSize: "2 Acres",
        CampusType: "Urban",
        RegistrationFees: "₹25",
        AdmissionFees: "₹200",
        TuitionFees: "₹3,175",
        AnnualFees: "₹7,500",
        DevelopmentFees: "₹5,715",
        TransportationFees: "₹2,000-3,000",
        otherFees: "₹16,500",
        MiscFees: "₹5,000",
        TotalCost: "₹73,040",
        MonthyCost: "₹6,069",
        classesOffered: "Play Way- Class 12",
        LanguageOfInstruction: "English",
        AcademicSession: "April To March",
        SchoolFormat: "Day School",
        StudentFacultyRatio: "12:1",
        EligibilityCriteria: "NA",
        WrittenTest: "No",
        TotalSeats: 75,
        ParentsInteraction: "No",
        FormAvailability: "online",
        FormPayment: "online",
        SchoolTiming: "07:40AM TO 12:30PM",
        officeTiming: "NA",
        TotalCost: "₹1,23,925",
        MonthyCost: "₹10,309"


    },
    {
        id: 14,
        name: "Ram Das School",
        address: "Nagpur",
        imgUrl: "https://images.livemint.com/img/2021/07/01/600x338/MP2-kYiB--621x414@LiveMint_1625139958457.jpg",
        fees: "10,200",
        board: "CBSE",
        classes: "1-12",
        category: "Nagpur",
        ownership: "Private",
        YearOfEstablishment: 1984,
        coedStatus: "Co-Education",
        CampusSize: "2 Acres",
        CampusType: "Urban",
        RegistrationFees: "₹25",
        AdmissionFees: "₹200",
        TuitionFees: "₹3,175",
        AnnualFees: "₹7,500",
        DevelopmentFees: "₹5,715",
        TransportationFees: "₹2,000-3,000",
        otherFees: "₹16,500",
        MiscFees: "₹5,000",
        TotalCost: "₹73,040",
        MonthyCost: "₹6,069",
        classesOffered: "Play Way- Class 12",
        LanguageOfInstruction: "English",
        AcademicSession: "April To March",
        SchoolFormat: "Day School",
        StudentFacultyRatio: "12:1",
        EligibilityCriteria: "NA",
        WrittenTest: "No",
        TotalSeats: 75,
        ParentsInteraction: "No",
        FormAvailability: "online",
        FormPayment: "online",
        SchoolTiming: "07:40AM TO 12:30PM",
        officeTiming: "NA",
        TotalCost: "₹1,23,925",
        MonthyCost: "₹10,309"


    },
    {
        id: 15,
        name: "Gyandeep sr. sec. school",
        address: "Sector 18A,Dwarka,Delhi",
        imgUrl: "https://www.kasigaschool.com/wp-content/uploads/2019/12/Boarding-life-400x257.jpg",
        fees: "10,500",
        board: "CBSE",
        classes: "1-12",
        category: "Delhi",
        ownership: "Private",
        YearOfEstablishment: 1984,
        coedStatus: "Co-Education",
        CampusSize: "2 Acres",
        CampusType: "Urban",
        RegistrationFees: "₹25",
        AdmissionFees: "₹200",
        TuitionFees: "₹3,175",
        AnnualFees: "₹7,500",
        DevelopmentFees: "₹5,715",
        TransportationFees: "₹2,000-3,000",
        otherFees: "₹16,500",
        MiscFees: "₹5,000",
        TotalCost: "₹73,040",
        MonthyCost: "₹6,069",
        classesOffered: "Play Way- Class 12",
        LanguageOfInstruction: "English",
        AcademicSession: "April To March",
        SchoolFormat: "Day School",
        StudentFacultyRatio: "12:1",
        EligibilityCriteria: "NA",
        WrittenTest: "No",
        TotalSeats: 75,
        ParentsInteraction: "No",
        FormAvailability: "online",
        FormPayment: "online",
        SchoolTiming: "07:40AM TO 12:30PM",
        officeTiming: "NA",
        TotalCost: "₹1,23,925",
        MonthyCost: "₹10,309"


    },
    {
        id: 16,
        name: "Kids corner happy sr. sec. school",
        address: "Near jain mandir,Firozabad",
        imgUrl: "https://rbkei.org/wp-content/uploads/2021/01/School-Slider-03.jpg",
        fees: "10,800",
        board: "CBSE",
        classes: "1-12",
        category: "Agra",
        ownership: "Private",
        YearOfEstablishment: 1984,
        coedStatus: "Co-Education",
        CampusSize: "2 Acres",
        CampusType: "Urban",
        RegistrationFees: "₹25",
        AdmissionFees: "₹200",
        TuitionFees: "₹3,175",
        AnnualFees: "₹7,500",
        DevelopmentFees: "₹5,715",
        TransportationFees: "₹2,000-3,000",
        otherFees: "₹16,500",
        MiscFees: "₹5,000",
        TotalCost: "₹73,040",
        MonthyCost: "₹6,069",
        classesOffered: "Play Way- Class 12",
        LanguageOfInstruction: "English",
        AcademicSession: "April To March",
        SchoolFormat: "Day School",
        StudentFacultyRatio: "12:1",
        EligibilityCriteria: "NA",
        WrittenTest: "No",
        TotalSeats: 75,
        ParentsInteraction: "No",
        FormAvailability: "online",
        FormPayment: "online",
        SchoolTiming: "07:40AM TO 12:30PM",
        officeTiming: "NA",
        TotalCost: "₹1,23,925",
        MonthyCost: "₹10,309"


    },
    {
        id: 17,
        name: "Kids corner happy sr. sec. school",
        address: "Near jain mandir,Firozabad",
        imgUrl: "https://rbkei.org/wp-content/uploads/2021/01/School-Slider-03.jpg",
        fees: "10,800",
        board: "CBSE",
        classes: "1-12",
        category: "Agra",
        ownership: "Private",
        YearOfEstablishment: 1984,
        coedStatus: "Co-Education",
        CampusSize: "2 Acres",
        CampusType: "Urban",
        RegistrationFees: "₹25",
        AdmissionFees: "₹200",
        TuitionFees: "₹3,175",
        AnnualFees: "₹7,500",
        DevelopmentFees: "₹5,715",
        TransportationFees: "₹2,000-3,000",
        otherFees: "₹16,500",
        MiscFees: "₹5,000",
        TotalCost: "₹73,040",
        MonthyCost: "₹6,069",
        classesOffered: "Play Way- Class 12",
        LanguageOfInstruction: "English",
        AcademicSession: "April To March",
        SchoolFormat: "Day School",
        StudentFacultyRatio: "12:1",
        EligibilityCriteria: "NA",
        WrittenTest: "No",
        TotalSeats: 75,
        ParentsInteraction: "No",
        FormAvailability: "online",
        FormPayment: "online",
        SchoolTiming: "07:40AM TO 12:30PM",
        officeTiming: "NA",
        TotalCost: "₹1,23,925",
        MonthyCost: "₹10,309"


    },
    {
        id: 18,
        name: "Kids corner happy sr. sec. school",
        address: "Near jain mandir,Firozabad",
        imgUrl: "https://rbkei.org/wp-content/uploads/2021/01/School-Slider-03.jpg",
        fees: "10,800",
        board: "CBSE",
        classes: "1-12",
        category: "Agra",
        ownership: "Private",
        YearOfEstablishment: 1984,
        coedStatus: "Co-Education",
        CampusSize: "2 Acres",
        CampusType: "Urban",
        RegistrationFees: "₹25",
        AdmissionFees: "₹200",
        TuitionFees: "₹3,175",
        AnnualFees: "₹7,500",
        DevelopmentFees: "₹5,715",
        TransportationFees: "₹2,000-3,000",
        otherFees: "₹16,500",
        MiscFees: "₹5,000",
        TotalCost: "₹73,040",
        MonthyCost: "₹6,069",
        classesOffered: "Play Way- Class 12",
        LanguageOfInstruction: "English",
        AcademicSession: "April To March",
        SchoolFormat: "Day School",
        StudentFacultyRatio: "12:1",
        EligibilityCriteria: "NA",
        WrittenTest: "No",
        TotalSeats: 75,
        ParentsInteraction: "No",
        FormAvailability: "online",
        FormPayment: "online",
        SchoolTiming: "07:40AM TO 12:30PM",
        officeTiming: "NA",
        TotalCost: "₹1,23,925",
        MonthyCost: "₹10,309"


    },
    {
        id: 19,
        name: "Kids corner happy sr. sec. school",
        address: "Near jain mandir,Firozabad",
        imgUrl: "https://rbkei.org/wp-content/uploads/2021/01/School-Slider-03.jpg",
        fees: "10,800",
        board: "CBSE",
        classes: "1-12",
        category: "Agra",
        ownership: "Private",
        YearOfEstablishment: 1984,
        coedStatus: "Co-Education",
        CampusSize: "2 Acres",
        CampusType: "Urban",
        RegistrationFees: "₹25",
        AdmissionFees: "₹200",
        TuitionFees: "₹3,175",
        AnnualFees: "₹7,500",
        DevelopmentFees: "₹5,715",
        TransportationFees: "₹2,000-3,000",
        otherFees: "₹16,500",
        MiscFees: "₹5,000",
        TotalCost: "₹73,040",
        MonthyCost: "₹6,069",
        classesOffered: "Play Way- Class 12",
        LanguageOfInstruction: "English",
        AcademicSession: "April To March",
        SchoolFormat: "Day School",
        StudentFacultyRatio: "12:1",
        EligibilityCriteria: "NA",
        WrittenTest: "No",
        TotalSeats: 75,
        ParentsInteraction: "No",
        FormAvailability: "online",
        FormPayment: "online",
        SchoolTiming: "07:40AM TO 12:30PM",
        officeTiming: "NA",
        TotalCost: "₹1,23,925",
        MonthyCost: "₹10,309"


    }, {
        id: 20,
        name: "Kids corner happy sr. sec. school",
        address: "Near jain mandir,Firozabad",
        imgUrl: "https://rbkei.org/wp-content/uploads/2021/01/School-Slider-03.jpg",
        fees: "10,800",
        board: "CBSE",
        classes: "1-12",
        category: "Agra",
        ownership: "Private",
        YearOfEstablishment: 1984,
        coedStatus: "Co-Education",
        CampusSize: "2 Acres",
        CampusType: "Urban",
        RegistrationFees: "₹25",
        AdmissionFees: "₹200",
        TuitionFees: "₹3,175",
        AnnualFees: "₹7,500",
        DevelopmentFees: "₹5,715",
        TransportationFees: "₹2,000-3,000",
        otherFees: "₹16,500",
        MiscFees: "₹5,000",
        TotalCost: "₹73,040",
        MonthyCost: "₹6,069",
        classesOffered: "Play Way- Class 12",
        LanguageOfInstruction: "English",
        AcademicSession: "April To March",
        SchoolFormat: "Day School",
        StudentFacultyRatio: "12:1",
        EligibilityCriteria: "NA",
        WrittenTest: "No",
        TotalSeats: 75,
        ParentsInteraction: "No",
        FormAvailability: "online",
        FormPayment: "online",
        SchoolTiming: "07:40AM TO 12:30PM",
        officeTiming: "NA",
        TotalCost: "₹1,23,925",
        MonthyCost: "₹10,309"


    },
    {
        id: 21,
        name: "Gyandeep sr. sec. school",
        address: "Sector 18A,Dwarka,Delhi",
        imgUrl: "https://www.kasigaschool.com/wp-content/uploads/2019/12/Boarding-life-400x257.jpg",
        fees: "10,500",
        board: "CBSE",
        classes: "1-12",
        category: "Delhi",
        ownership: "Private",
        YearOfEstablishment: 1984,
        coedStatus: "Co-Education",
        CampusSize: "2 Acres",
        CampusType: "Urban",
        RegistrationFees: "₹25",
        AdmissionFees: "₹200",
        TuitionFees: "₹3,175",
        AnnualFees: "₹7,500",
        DevelopmentFees: "₹5,715",
        TransportationFees: "₹2,000-3,000",
        otherFees: "₹16,500",
        MiscFees: "₹5,000",
        TotalCost: "₹73,040",
        MonthyCost: "₹6,069",
        classesOffered: "Play Way- Class 12",
        LanguageOfInstruction: "English",
        AcademicSession: "April To March",
        SchoolFormat: "Day School",
        StudentFacultyRatio: "12:1",
        EligibilityCriteria: "NA",
        WrittenTest: "No",
        TotalSeats: 75,
        ParentsInteraction: "No",
        FormAvailability: "online",
        FormPayment: "online",
        SchoolTiming: "07:40AM TO 12:30PM",
        officeTiming: "NA",
        TotalCost: "₹1,23,925",
        MonthyCost: "₹10,309"


    },
    {
        id: 22,
        name: "Gyandeep sr. sec. school",
        address: "Sector 18A,Dwarka,Delhi",
        imgUrl: "https://www.kasigaschool.com/wp-content/uploads/2019/12/Boarding-life-400x257.jpg",
        fees: "10,500",
        board: "CBSE",
        classes: "1-12",
        category: "Delhi",
        ownership: "Private",
        YearOfEstablishment: 1984,
        coedStatus: "Co-Education",
        CampusSize: "2 Acres",
        CampusType: "Urban",
        RegistrationFees: "₹25",
        AdmissionFees: "₹200",
        TuitionFees: "₹3,175",
        AnnualFees: "₹7,500",
        DevelopmentFees: "₹5,715",
        TransportationFees: "₹2,000-3,000",
        otherFees: "₹16,500",
        MiscFees: "₹5,000",
        TotalCost: "₹73,040",
        MonthyCost: "₹6,069",
        classesOffered: "Play Way- Class 12",
        LanguageOfInstruction: "English",
        AcademicSession: "April To March",
        SchoolFormat: "Day School",
        StudentFacultyRatio: "12:1",
        EligibilityCriteria: "NA",
        WrittenTest: "No",
        TotalSeats: 75,
        ParentsInteraction: "No",
        FormAvailability: "online",
        FormPayment: "online",
        SchoolTiming: "07:40AM TO 12:30PM",
        officeTiming: "NA",
        TotalCost: "₹1,23,925",
        MonthyCost: "₹10,309"


    },
    {
        id: 23,
        name: "Gyandeep sr. sec. school",
        address: "Sector 18A,Dwarka,Delhi",
        imgUrl: "https://www.kasigaschool.com/wp-content/uploads/2019/12/Boarding-life-400x257.jpg",
        fees: "10,500",
        board: "CBSE",
        classes: "1-12",
        category: "Delhi",
        ownership: "Private",
        YearOfEstablishment: 1984,
        coedStatus: "Co-Education",
        CampusSize: "2 Acres",
        CampusType: "Urban",
        RegistrationFees: "₹25",
        AdmissionFees: "₹200",
        TuitionFees: "₹3,175",
        AnnualFees: "₹7,500",
        DevelopmentFees: "₹5,715",
        TransportationFees: "₹2,000-3,000",
        otherFees: "₹16,500",
        MiscFees: "₹5,000",
        TotalCost: "₹73,040",
        MonthyCost: "₹6,069",
        classesOffered: "Play Way- Class 12",
        LanguageOfInstruction: "English",
        AcademicSession: "April To March",
        SchoolFormat: "Day School",
        StudentFacultyRatio: "12:1",
        EligibilityCriteria: "NA",
        WrittenTest: "No",
        TotalSeats: 75,
        ParentsInteraction: "No",
        FormAvailability: "online",
        FormPayment: "online",
        SchoolTiming: "07:40AM TO 12:30PM",
        officeTiming: "NA",
        TotalCost: "₹1,23,925",
        MonthyCost: "₹10,309"


    },
    {
        id: 24,
        name: "Gyandeep sr. sec. school",
        address: "Sector 18A,Dwarka,Delhi",
        imgUrl: "https://www.kasigaschool.com/wp-content/uploads/2019/12/Boarding-life-400x257.jpg",
        fees: "10,500",
        board: "CBSE",
        classes: "1-12",
        category: "Delhi",
        ownership: "Private",
        YearOfEstablishment: 1984,
        coedStatus: "Co-Education",
        CampusSize: "2 Acres",
        CampusType: "Urban",
        RegistrationFees: "₹25",
        AdmissionFees: "₹200",
        TuitionFees: "₹3,175",
        AnnualFees: "₹7,500",
        DevelopmentFees: "₹5,715",
        TransportationFees: "₹2,000-3,000",
        otherFees: "₹16,500",
        MiscFees: "₹5,000",
        TotalCost: "₹73,040",
        MonthyCost: "₹6,069",
        classesOffered: "Play Way- Class 12",
        LanguageOfInstruction: "English",
        AcademicSession: "April To March",
        SchoolFormat: "Day School",
        StudentFacultyRatio: "12:1",
        EligibilityCriteria: "NA",
        WrittenTest: "No",
        TotalSeats: 75,
        ParentsInteraction: "No",
        FormAvailability: "online",
        FormPayment: "online",
        SchoolTiming: "07:40AM TO 12:30PM",
        officeTiming: "NA",
        TotalCost: "₹1,23,925",
        MonthyCost: "₹10,309"


    },
    {
        id: 25,
        name: "St. Johns School",
        address: "Ghaziabad",
        imgUrl: "https://images.livemint.com/img/2021/07/01/600x338/MP2-kYiB--621x414@LiveMint_1625139958457.jpg",
        fees: "10,200",
        board: "CBSE",
        classes: "1-12",
        category: "Ghaziabad",
        ownership: "Private",
        YearOfEstablishment: 1984,
        coedStatus: "Co-Education",
        CampusSize: "2 Acres",
        CampusType: "Urban",
        RegistrationFees: "₹25",
        AdmissionFees: "₹200",
        TuitionFees: "₹3,175",
        AnnualFees: "₹7,500",
        DevelopmentFees: "₹5,715",
        TransportationFees: "₹2,000-3,000",
        otherFees: "₹16,500",
        MiscFees: "₹5,000",
        TotalCost: "₹73,040",
        MonthyCost: "₹6,069",
        classesOffered: "Play Way- Class 12",
        LanguageOfInstruction: "English",
        AcademicSession: "April To March",
        SchoolFormat: "Day School",
        StudentFacultyRatio: "12:1",
        EligibilityCriteria: "NA",
        WrittenTest: "No",
        TotalSeats: 75,
        ParentsInteraction: "No",
        FormAvailability: "online",
        FormPayment: "online",
        SchoolTiming: "07:40AM TO 12:30PM",
        officeTiming: "NA",
        TotalCost: "₹1,23,925",
        MonthyCost: "₹10,309"


    },
    {
        id: 26,
        name: "St. Johns School",
        address: "Ghaziabad",
        imgUrl: "https://images.livemint.com/img/2021/07/01/600x338/MP2-kYiB--621x414@LiveMint_1625139958457.jpg",
        fees: "10,200",
        board: "CBSE",
        classes: "1-12",
        category: "Ghaziabad",
        ownership: "Private",
        YearOfEstablishment: 1984,
        coedStatus: "Co-Education",
        CampusSize: "2 Acres",
        CampusType: "Urban",
        RegistrationFees: "₹25",
        AdmissionFees: "₹200",
        TuitionFees: "₹3,175",
        AnnualFees: "₹7,500",
        DevelopmentFees: "₹5,715",
        TransportationFees: "₹2,000-3,000",
        otherFees: "₹16,500",
        MiscFees: "₹5,000",
        TotalCost: "₹73,040",
        MonthyCost: "₹6,069",
        classesOffered: "Play Way- Class 12",
        LanguageOfInstruction: "English",
        AcademicSession: "April To March",
        SchoolFormat: "Day School",
        StudentFacultyRatio: "12:1",
        EligibilityCriteria: "NA",
        WrittenTest: "No",
        TotalSeats: 75,
        ParentsInteraction: "No",
        FormAvailability: "online",
        FormPayment: "online",
        SchoolTiming: "07:40AM TO 12:30PM",
        officeTiming: "NA",
        TotalCost: "₹1,23,925",
        MonthyCost: "₹10,309"


    },
    {
        id: 27,
        name: "St. Johns School",
        address: "Ghaziabad",
        imgUrl: "https://images.livemint.com/img/2021/07/01/600x338/MP2-kYiB--621x414@LiveMint_1625139958457.jpg",
        fees: "10,200",
        board: "CBSE",
        classes: "1-12",
        category: "Ghaziabad",
        ownership: "Private",
        YearOfEstablishment: 1984,
        coedStatus: "Co-Education",
        CampusSize: "2 Acres",
        CampusType: "Urban",
        RegistrationFees: "₹25",
        AdmissionFees: "₹200",
        TuitionFees: "₹3,175",
        AnnualFees: "₹7,500",
        DevelopmentFees: "₹5,715",
        TransportationFees: "₹2,000-3,000",
        otherFees: "₹16,500",
        MiscFees: "₹5,000",
        TotalCost: "₹73,040",
        MonthyCost: "₹6,069",
        classesOffered: "Play Way- Class 12",
        LanguageOfInstruction: "English",
        AcademicSession: "April To March",
        SchoolFormat: "Day School",
        StudentFacultyRatio: "12:1",
        EligibilityCriteria: "NA",
        WrittenTest: "No",
        TotalSeats: 75,
        ParentsInteraction: "No",
        FormAvailability: "online",
        FormPayment: "online",
        SchoolTiming: "07:40AM TO 12:30PM",
        officeTiming: "NA",
        TotalCost: "₹1,23,925",
        MonthyCost: "₹10,309"


    },
    {
        id: 28,
        name: "Ram Das School",
        address: "Nagpur",
        imgUrl: "https://images.livemint.com/img/2021/07/01/600x338/MP2-kYiB--621x414@LiveMint_1625139958457.jpg",
        fees: "10,200",
        board: "CBSE",
        classes: "1-12",
        category: "Nagpur",
        ownership: "Private",
        YearOfEstablishment: 1984,
        coedStatus: "Co-Education",
        CampusSize: "2 Acres",
        CampusType: "Urban",
        RegistrationFees: "₹25",
        AdmissionFees: "₹200",
        TuitionFees: "₹3,175",
        AnnualFees: "₹7,500",
        DevelopmentFees: "₹5,715",
        TransportationFees: "₹2,000-3,000",
        otherFees: "₹16,500",
        MiscFees: "₹5,000",
        TotalCost: "₹73,040",
        MonthyCost: "₹6,069",
        classesOffered: "Play Way- Class 12",
        LanguageOfInstruction: "English",
        AcademicSession: "April To March",
        SchoolFormat: "Day School",
        StudentFacultyRatio: "12:1",
        EligibilityCriteria: "NA",
        WrittenTest: "No",
        TotalSeats: 75,
        ParentsInteraction: "No",
        FormAvailability: "online",
        FormPayment: "online",
        SchoolTiming: "07:40AM TO 12:30PM",
        officeTiming: "NA",
        TotalCost: "₹1,23,925",
        MonthyCost: "₹10,309"


    },
    {
        id: 29,
        name: "Ram Das School",
        address: "Nagpur",
        imgUrl: "https://images.livemint.com/img/2021/07/01/600x338/MP2-kYiB--621x414@LiveMint_1625139958457.jpg",
        fees: "10,200",
        board: "CBSE",
        classes: "1-12",
        category: "Nagpur",
        ownership: "Private",
        YearOfEstablishment: 1984,
        coedStatus: "Co-Education",
        CampusSize: "2 Acres",
        CampusType: "Urban",
        RegistrationFees: "₹25",
        AdmissionFees: "₹200",
        TuitionFees: "₹3,175",
        AnnualFees: "₹7,500",
        DevelopmentFees: "₹5,715",
        TransportationFees: "₹2,000-3,000",
        otherFees: "₹16,500",
        MiscFees: "₹5,000",
        TotalCost: "₹73,040",
        MonthyCost: "₹6,069",
        classesOffered: "Play Way- Class 12",
        LanguageOfInstruction: "English",
        AcademicSession: "April To March",
        SchoolFormat: "Day School",
        StudentFacultyRatio: "12:1",
        EligibilityCriteria: "NA",
        WrittenTest: "No",
        TotalSeats: 75,
        ParentsInteraction: "No",
        FormAvailability: "online",
        FormPayment: "online",
        SchoolTiming: "07:40AM TO 12:30PM",
        officeTiming: "NA",
        TotalCost: "₹1,23,925",
        MonthyCost: "₹10,309"


    },
    {
        id: 30,
        name: "Ram Das School",
        address: "Nagpur",
        imgUrl: "https://images.livemint.com/img/2021/07/01/600x338/MP2-kYiB--621x414@LiveMint_1625139958457.jpg",
        fees: "10,200",
        board: "CBSE",
        classes: "1-12",
        category: "Nagpur",
        ownership: "Private",
        YearOfEstablishment: 1984,
        coedStatus: "Co-Education",
        CampusSize: "2 Acres",
        CampusType: "Urban",
        RegistrationFees: "₹25",
        AdmissionFees: "₹200",
        TuitionFees: "₹3,175",
        AnnualFees: "₹7,500",
        DevelopmentFees: "₹5,715",
        TransportationFees: "₹2,000-3,000",
        otherFees: "₹16,500",
        MiscFees: "₹5,000",
        TotalCost: "₹73,040",
        MonthyCost: "₹6,069",
        classesOffered: "Play Way- Class 12",
        LanguageOfInstruction: "English",
        AcademicSession: "April To March",
        SchoolFormat: "Day School",
        StudentFacultyRatio: "12:1",
        EligibilityCriteria: "NA",
        WrittenTest: "No",
        TotalSeats: 75,
        ParentsInteraction: "No",
        FormAvailability: "online",
        FormPayment: "online",
        SchoolTiming: "07:40AM TO 12:30PM",
        officeTiming: "NA"


    },
]
